package org.nearbyshops.gidb.DAOsPreparedRoles;

import com.zaxxer.hikari.HikariDataSource;
import org.nearbyshops.gidb.Globals.Globals;
import org.nearbyshops.gidb.ModelRoles.Admin;
import org.nearbyshops.gidb.ModelRoles.Usernames;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;


public class AdminDAOPrepared {


	private HikariDataSource dataSource = Globals.getDataSource();


	@Override
	protected void finalize() throws Throwable {
		// TODO Auto-generated method stub
		super.finalize();
	}


//	public int saveAdmin(Admin admin) {
//
//		Connection connection = null;
//		PreparedStatement statement = null;
//		int rowIdOfInsertedRow = -1;
//
//		String insertEndUser = "INSERT INTO "
//				+ Admin.TABLE_NAME
//				+ "("
//				+ Admin.ADMIN_NAME + ","
//				+ Admin.USER_NAME + ","
//				+ Admin.PASSWORD + ","
//				+ Admin.ABOUT + ","
//				+ Admin.PROFILE_IMAGE_URL
//				+ ") VALUES(?,?,?, ?,?)";
//
//		try {
//
//			connection = dataSource.getConnection();
//
//			statement = connection.prepareStatement(insertEndUser, PreparedStatement.RETURN_GENERATED_KEYS);
//
//			statement.setString(1, admin.getAdministratorName());
//			statement.setString(2, admin.getUsername());
//			statement.setString(3, admin.getPassword());
//
//			statement.setString(4,admin.getAbout());
//			statement.setString(5,admin.getProfileImageURL());
//
//			rowIdOfInsertedRow = statement.executeUpdate();
//
//			ResultSet rs = statement.getGeneratedKeys();
//
//			if (rs.next()) {
//				rowIdOfInsertedRow = rs.getInt(1);
//			}
//
//
//			System.out.println("Key autogenerated SaveDistributor: " + rowIdOfInsertedRow);
//
//
//		} catch (SQLException e) {
//			// TODO Auto-generated catch block
//			e.printStackTrace();
//		} finally {
//
//			try {
//
//				if (statement != null) {
//					statement.close();
//				}
//			} catch (SQLException e) {
//				// TODO Auto-generated catch block
//				e.printStackTrace();
//			}
//
//			try {
//
//				if (connection != null) {
//					connection.close();
//				}
//			} catch (SQLException e) {
//				// TODO Auto-generated catch block
//				e.printStackTrace();
//			}
//		}
//
//
//		return rowIdOfInsertedRow;
//	}


	public int saveDefaultAdmin(Admin admin) {

		Connection connection = null;
		PreparedStatement statement = null;
		PreparedStatement statementUsername = null;
//		int rowIdOfInsertedRow = -1;
		int rowIdUserID = -1;



		String insertUsername = "INSERT INTO "
				+ Usernames.TABLE_NAME
				+ "("
				+ Usernames.USERNAME + ""
//				+ Usernames.USER_ID + ""
				+ ") VALUES(?)";


		String insertEndUser = "INSERT INTO "
				+ Admin.TABLE_NAME
				+ "("
				+ Admin.ADMIN_NAME + ","
//				+ Admin.USER_NAME + ","
				+ Admin.PASSWORD + ","
				+ Admin.ADMIN_ID
				+ ") VALUES(?,?,?)";

		try {

			connection = dataSource.getConnection();
			connection.setAutoCommit(false);


			statementUsername = connection.prepareStatement(insertUsername,PreparedStatement.RETURN_GENERATED_KEYS);
			statementUsername.setString(1,admin.getUsername());
//			statementUsername.setInt(2,1);
			statementUsername.executeUpdate();

			ResultSet rs2 = statementUsername.getGeneratedKeys();

			if (rs2.next()) {
				rowIdUserID = rs2.getInt(1);
			}



			statement = connection.prepareStatement(insertEndUser, PreparedStatement.RETURN_GENERATED_KEYS);

			int i = 0;
			statement.setString(++i, admin.getAdministratorName());
//			statement.setString(++i, admin.getUsername());
			statement.setString(++i, admin.getPassword());
			statement.setInt(++i,rowIdUserID);

			statement.executeUpdate();

//			ResultSet rs = statement.getGeneratedKeys();
//
//			if (rs.next()) {
//				rowIdOfInsertedRow = rs.getInt(1);
//			}
//

			System.out.println("Key autogenerated: " + rowIdUserID);


			connection.commit();

		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();

			if (connection != null) {
				try {

					rowIdUserID = -1;
					connection.rollback();
				} catch (SQLException e1) {
					e1.printStackTrace();
				}
			}

		} finally {




			if (statementUsername != null) {
				try {

					statementUsername.close();
				} catch (SQLException e) {
					e.printStackTrace();
				}
			}


			try {

				if (statement != null) {
					statement.close();
				}
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}

			try {

				if (connection != null) {
					connection.close();
				}
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}


		return rowIdUserID;
	}




	public int updateAdmin(Admin admin) {


		String updateUsername = "UPDATE " + Usernames.TABLE_NAME
				+ " SET " + Usernames.USERNAME + " = ?"
				+ " WHERE " + Usernames.USER_ID + " = ?";



		String updateStatement = "UPDATE " + Admin.TABLE_NAME
				+ " SET "
				+ Admin.ADMIN_NAME + " = ?,"
//				+ Admin.USER_NAME + " = ?,"
				+ Admin.PASSWORD + " = ?,"

				+ Admin.ABOUT + " = ?,"
				+ Admin.PROFILE_IMAGE_URL + " = ?,"

				+ Admin.PHONE_NUMBER + " = ?,"
				+ Admin.DESIGNATION + " = ?,"
				+ Admin.ACCOUNT_PRIVATE + " = ?"

				+ " WHERE " + Admin.ADMIN_ID + " = ?";

		Connection connection = null;
		PreparedStatement statement = null;
		PreparedStatement statementUsername = null;
		int updatedRows = -1;

		try {

			connection = dataSource.getConnection();
			connection.setAutoCommit(false);

			statementUsername = connection.prepareStatement(updateUsername, PreparedStatement.RETURN_GENERATED_KEYS);
			statementUsername.setString(1,admin.getUsername());
			statementUsername.setInt(2,admin.getAdminID());
			statementUsername.executeUpdate();


			statement = connection.prepareStatement(updateStatement, PreparedStatement.RETURN_GENERATED_KEYS);
			int i = 0;
			statement.setString(++i, admin.getAdministratorName());
//			statement.setString(++i, admin.getUsername());
			statement.setString(++i, admin.getPassword());

			statement.setString(++i,admin.getAbout());
			statement.setString(++i,admin.getProfileImageURL());

			statement.setString(++i,admin.getPhone());
			statement.setString(++i,admin.getDesignation());
			statement.setObject(++i,admin.isAccountPrivate());

			statement.setObject(++i, admin.getAdminID());

			updatedRows = statement.executeUpdate();


			System.out.println("Total rows updated: " + updatedRows);

			//conn.close();

			connection.commit();

		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();

			if (connection != null) {
				try {
					connection.rollback();
				} catch (SQLException e1) {
					e1.printStackTrace();
				}
			}


		} finally

		{

			if (statementUsername != null) {
				try {
					statementUsername.close();
				} catch (SQLException e) {
					e.printStackTrace();
				}
			}


			try {

				if (statement != null) {
					statement.close();
				}
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}

			try {

				if (connection != null) {
					connection.close();
				}
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}

		return updatedRows;

	}


	public List<Admin> getAdmin(String username, Integer admin_id)
	{
		boolean isFirst = true;

		String query = "SELECT "
						+ Admin.ADMIN_ID + ","
						+ Usernames.USERNAME + ","
						+ Admin.PASSWORD + ","
						+ Admin.ADMIN_NAME + ","
						+ Admin.ABOUT + ","
						+ Admin.PROFILE_IMAGE_URL + ","
						+ Admin.PHONE_NUMBER + ","
						+ Admin.DESIGNATION + ","
						+ Admin.ACCOUNT_PRIVATE + ","
						+ Admin.TIMESTAMP_CREATED + ""

						+ " FROM " + Admin.TABLE_NAME
						+ " INNER JOIN " + Usernames.TABLE_NAME + " ON (" + Admin.ADMIN_ID + " = " + Usernames.USER_ID + ")";


		if(username!=null)
		{
			query = query + " WHERE " + Usernames.USERNAME + " = ?";
			isFirst = false;
		}


		if(admin_id!=null)
		{
			String queryPart = Admin.ADMIN_ID + " = ?";

			if(isFirst)
			{
				query = query + " WHERE " + queryPart;
				isFirst = false;
			}
			else
			{
				query = query + " AND " + queryPart;
			}
		}




		Connection connection = null;
		PreparedStatement statement = null;
		ResultSet rs = null;


		//Distributor distributor = null;
		List<Admin> adminList = new ArrayList<>();

		try {

			connection = dataSource.getConnection();
			statement = connection.prepareStatement(query);

			int i = 0;
			if(username!=null)
			{
				statement.setString(++i,username);
			}

			if(admin_id!=null)
			{
				statement.setInt(++i,admin_id);
			}

			rs = statement.executeQuery();

			while (rs.next()) {

				Admin admin = new Admin();

				admin.setAdminID(rs.getInt(Admin.ADMIN_ID));
				admin.setAdministratorName(rs.getString(Admin.ADMIN_NAME));
				admin.setUsername(rs.getString(Usernames.USERNAME));
				admin.setPassword(rs.getString(Admin.PASSWORD));

				admin.setAbout(rs.getString(Admin.ABOUT));
				admin.setProfileImageURL(rs.getString(Admin.PROFILE_IMAGE_URL));

				admin.setPhone(rs.getString(Admin.PHONE_NUMBER));
				admin.setDesignation(rs.getString(Admin.DESIGNATION));

				admin.setAccountPrivate(rs.getBoolean(Admin.ACCOUNT_PRIVATE));
				admin.setTimestampCreated(rs.getTimestamp(Admin.TIMESTAMP_CREATED));

				adminList.add(admin);
			}


			//System.out.println("Total itemCategories queried " + itemCategoryList.size());	


		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} finally

		{

			try {
				if (rs != null) {
					rs.close();
				}
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}

			try {

				if (statement != null) {
					statement.close();
				}
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}

			try {

				if (connection != null) {
					connection.close();
				}
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}

		return adminList;
	}


	public void logMessage(String message)
	{
		System.out.println(message);
	}




	public Admin checkAdmin(String username, String password)
	{


//		logMessage("Checking Admin");


		boolean isFirst = true;

		String query = 	" SELECT " + Admin.ADMIN_ID + "," + Usernames.USERNAME + "," + Admin.PASSWORD + "," + Admin.ADMIN_NAME +
						" FROM " + Admin.TABLE_NAME +
						" INNER JOIN " + Usernames.TABLE_NAME + " ON (" + Admin.ADMIN_ID + " = " + Usernames.USER_ID + ")";

//		if(adminID!=null)
//		{
//			query = query + " WHERE " + Admin.ADMIN_ID + " = " + adminID;
//
//			isFirst = false;
//		}

		if(username!=null)
		{
			String queryPartUsername = Usernames.USERNAME + " = ? ";
			query = query + " WHERE " + queryPartUsername;
			isFirst = false;
		}


		if(password!=null)
		{
			String queryPartPassword = Admin.PASSWORD + " = ? ";

			if(isFirst)
			{
				query = query + " WHERE " + queryPartPassword;
			}
			else
			{
				query = query + " AND " + queryPartPassword;
			}
		}


//		logMessage(query);


		Connection connection = null;
		PreparedStatement statement = null;
		ResultSet rs = null;


		//Distributor distributor = null;
		Admin admin = null;

		try {

			connection = dataSource.getConnection();
			statement = connection.prepareStatement(query);

			statement.setObject(1,username);
			statement.setObject(2,password);

			rs = statement.executeQuery();

			while(rs.next())
			{
				admin = new Admin();

				logMessage("Inside check admin");
				admin.setAdminID(rs.getInt(Admin.ADMIN_ID));
				admin.setAdministratorName(rs.getString(Admin.ADMIN_NAME));
				admin.setUsername(rs.getString(Usernames.USERNAME));
				admin.setPassword(rs.getString(Admin.PASSWORD));
			}


			//System.out.println("Total itemCategories queried " + itemCategoryList.size());



		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} finally

		{

			try {
				if(rs!=null)
				{rs.close();}
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}

			try {

				if(statement!=null)
				{statement.close();}
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}

			try {

				if(connection!=null)
				{connection.close();}
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}

		return admin;
	}
}
